version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - ./backend/.env.dev
    ports:
      - 5432:5432
    
  redis:
    env_file:
      - ./backend/.env.dev
    image: redis:7-alpine
    ports:
    - "6379:6379"
  